//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBirEkimKutuphane.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitap()
        {
            this.iade = new HashSet<iade>();
            this.odunc = new HashSet<odunc>();
        }
    
        public int kitapID { get; set; }
        public string kitapAdi { get; set; }
        public short yazari { get; set; }
        public short kategori { get; set; }
        public string gorsel { get; set; }
        public bool durum { get; set; }
    
        public virtual kategori kategori1 { get; set; }
        public virtual yazar yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iade> iade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odunc> odunc { get; set; }
    }
}
