//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBirEkimKutuphane.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class odunc
    {
        public int oduncID { get; set; }
        public int kitap { get; set; }
        public int oduncalan { get; set; }
        public short oduncveren { get; set; }
        public System.DateTime verilmetarihi { get; set; }
        public System.DateTime tavsiyeedileniadetarihi { get; set; }
    
        public virtual kitap kitap1 { get; set; }
        public virtual personel personel { get; set; }
        public virtual uye uye { get; set; }
    }
}
